import 'dart:convert';

import '../ir/model.dart';
import 'types.dart';
import 'writer.dart';

const String _header =
    '// GENERATED by tool/generate.dart from tool/spec/brevo-openapi.json — do not edit by hand.\n';

final class GeneratedFile {
  const GeneratedFile(this.path, this.content);
  final String path;
  final String content;
}

final class Emitter {
  Emitter(this.ir) {
    for (final c in ir.classes.values) {
      _locations[c.className] = c.kind == ClassKind.request
          ? '${c.group}/requests.dart'
          : '${c.group}/models.dart';
    }
    for (final e in ir.enums.values) {
      _locations[e.enumName] = '${e.group}/enums.dart';
    }
    for (final namespace in ir.namespaces.values) {
      _locations[namespace.className] = '${namespace.name}/resource.dart';
      _operationsByKey
          .addEntries(namespace.operations.map((op) => MapEntry(op.key, op)));
    }
  }

  final GeneratorIr ir;
  final Map<String, String> _locations = {};
  final Map<String, OperationIr> _operationsByKey = {};

  List<GeneratedFile> emitAll() {
    final files = <GeneratedFile>[];
    final byFile = <String, List<Object>>{};
    for (final c in ir.classes.values) {
      byFile.putIfAbsent(_locations[c.className]!, () => []).add(c);
    }
    for (final e in ir.enums.values) {
      byFile.putIfAbsent(_locations[e.enumName]!, () => []).add(e);
    }
    for (final entry in byFile.entries) {
      files.add(GeneratedFile('lib/src/generated/${entry.key}',
          _emitDeclarations(entry.key, entry.value)));
    }
    for (final namespace in ir.namespaces.values) {
      files.add(GeneratedFile(
          'lib/src/generated/${_locations[namespace.className]}',
          _emitNamespace(namespace)));
    }
    files.add(GeneratedFile(
        'lib/src/generated/client_resources.dart', _emitClientResources()));
    files.add(GeneratedFile('lib/src/generated/generated.dart', _emitBarrel()));
    files.add(GeneratedFile(
        'test/generated/models_decode_test.dart', _emitDecodeTest()));
    files.add(GeneratedFile(
        'test/generated/operations_mock_test.dart', _emitMockTest()));
    files.add(GeneratedFile(
        'test/generated/response_examples.json', _emitResponseExamples()));
    files.sort((a, b) => a.path.compareTo(b.path));
    return files;
  }

  String _relative(String fromPath, String toPath) {
    final fromDir = fromPath.contains('/')
        ? fromPath.substring(0, fromPath.lastIndexOf('/'))
        : '';
    final fromParts = fromDir.isEmpty ? <String>[] : fromDir.split('/');
    final toParts = toPath.split('/');
    var common = 0;
    while (common < fromParts.length &&
        common < toParts.length - 1 &&
        fromParts[common] == toParts[common]) {
      common++;
    }
    final up = List.filled(fromParts.length - common, '..');
    return [...up, ...toParts.sublist(common)].join('/');
  }

  String _coreImport(String fromPath, String coreFile) =>
      _relative('generated/$fromPath', 'core/$coreFile');

  List<String> _imports(String fromPath, Set<String> typeNames,
      {Set<String> core = const {}, Set<String> dart = const {}}) {
    final dartLines = <String>{for (final name in dart) "import 'dart:$name';"};
    final packageLines = <String>{};
    for (final file in core) {
      packageLines.add("import '${_coreImport(fromPath, file)}';");
    }
    for (final name in typeNames) {
      final location = _locations[name];
      if (location == null) throw StateError('no generated file for $name');
      if (location == fromPath) continue;
      packageLines.add("import '${_relative(fromPath, location)}';");
    }
    return [
      ...dartLines.toList()..sort(),
      if (dartLines.isNotEmpty && packageLines.isNotEmpty) '',
      ...packageLines.toList()..sort()
    ];
  }

  String _emitDeclarations(String path, List<Object> declarations) {
    final w = DartWriter();
    final referenced = <String>{};
    final core = <String>{};
    var anyFields = false;
    var anyDecodeException = false;
    var anyFile = false;
    for (final declaration in declarations) {
      if (declaration is ClassIr) {
        for (final field in declaration.fields) {
          referenced.addAll(referencedTypeNames(field.type));
          if (field.type is IrFile) anyFile = true;
        }
        if (declaration.fields.isNotEmpty && !declaration.multipart) {
          anyFields = true;
        }
        if (needsDecodeException(declaration) && !declaration.multipart) {
          anyDecodeException = true;
        }
      } else if (declaration is EnumIr) {
        core.add('open_enum.dart');
      }
    }
    if (anyFields) core.add('json_reading.dart');
    if (anyDecodeException) core.add('decode_exception.dart');
    if (anyFile) core.add('multipart.dart');
    w.line(_header);
    final imports = _imports(path, referenced, core: core);
    if (imports.isNotEmpty) {
      imports.forEach(w.line);
      w.line();
    }
    final sorted = declarations.toList()
      ..sort((a, b) => _declarationName(a).compareTo(_declarationName(b)));
    var first = true;
    for (final declaration in sorted) {
      if (!first) {
        w.line();
      }
      first = false;
      if (declaration is ClassIr) {
        _emitClass(declaration, w);
      } else if (declaration is EnumIr) {
        _emitEnum(declaration, w);
      }
    }
    return w.toString();
  }

  String _declarationName(Object declaration) => switch (declaration) {
        ClassIr(:final className) => className,
        EnumIr(:final enumName) => enumName,
        _ => throw StateError('unexpected declaration $declaration'),
      };

  void _emitClass(ClassIr c, DartWriter w) {
    final isModel = c.kind == ClassKind.model;
    w.doc(c.docs,
        fallback: isModel
            ? 'The `${c.origin ?? c.className}` object of the Brevo API.'
            : 'The request body of `${c.origin ?? c.className}`.');
    w.block('final class ${c.className} {', () {
      w.doc(null,
          fallback: isModel
              ? 'Creates a ${c.className} from already-decoded fields.'
              : 'Creates the request body.');
      final constructorParams = <String>[];
      for (final field in c.fields) {
        if (field.required) {
          constructorParams.add('required this.${field.dartName},');
        } else if (isModel && field.type is IrList) {
          constructorParams.add('this.${field.dartName} = const [],');
        } else if (isModel && field.type is IrJsonMap) {
          constructorParams.add('this.${field.dartName} = const {},');
        } else {
          constructorParams.add('this.${field.dartName},');
        }
      }
      if (isModel) constructorParams.add('this.raw = const {},');
      if (constructorParams.isEmpty) {
        w.line('const ${c.className}();');
      } else {
        w.block(
            'const ${c.className}({', () => constructorParams.forEach(w.line),
            close: '});');
      }
      if (!c.multipart) {
        w.line();
        w.doc(null,
            fallback: isModel
                ? 'Decodes a JSON object into a ${c.className}. Every field is read tolerantly: one that is absent or has an unexpected type decodes to `null` (or an empty collection).'
                : 'Decodes a JSON object into a ${c.className}. Optional fields absent from [json] stay null.');
        if (c.fields.isEmpty && !isModel) {
          w.line(
              'factory ${c.className}.fromJson(Map<String, Object?> json) => const ${c.className}();');
        } else {
          w.block(
              'factory ${c.className}.fromJson(Map<String, Object?> json) => ${c.className}(',
              () {
            for (final field in c.fields) {
              w.line(
                  '${field.dartName}: ${decodeField(field, c.className, c.kind)},');
            }
            if (isModel) w.line('raw: json,');
          }, close: ');');
        }
      }
      for (final field in c.fields) {
        w.line();
        w.doc(field.docs, fallback: 'The `${field.wireName}` field.');
        if (field.deprecated) w.line("@Deprecated('Deprecated by Brevo.')");
        w.line('final ${fieldDartType(field, c.kind)} ${field.dartName};');
        if (field.hasDateGetter) {
          w.line();
          w.doc(null,
              fallback:
                  '[${field.dartName}] parsed as an instant, or `null` when absent or unparsable.');
          w.line(
              'DateTime? get ${field.dartName}Date => ${fieldIsNullable(field, c.kind) ? '${field.dartName} == null ? null : DateTime.tryParse(${field.dartName}!)' : 'DateTime.tryParse(${field.dartName})'};');
        }
      }
      if (isModel) {
        w.line();
        w.doc(null,
            fallback:
                'The whole decoded object, for fields not promoted to a property.');
        w.line('final Map<String, Object?> raw;');
      }
      w.line();
      if (c.multipart) {
        _emitMultipartEncoders(c, w);
      } else {
        _emitToJson(c, w);
      }
    });
  }

  void _emitToJson(ClassIr c, DartWriter w) {
    final isModel = c.kind == ClassKind.model;
    w.doc(null,
        fallback: isModel
            ? 'Encodes the object as JSON, omitting absent fields.'
            : 'Encodes the request body as JSON, omitting absent fields — a Dart `null` is never sent, exactly as `@getbrevo/brevo` drops `undefined`.');
    if (c.fields.isEmpty) {
      w.line('Map<String, Object?> toJson() => const <String, Object?>{};');
      return;
    }
    w.block('Map<String, Object?> toJson() => {', () {
      for (final field in c.fields) {
        final key = dartStringLiteral(field.wireName);
        final name = field.dartName;
        if (field.type is IrJson) {
          w.line('if ($name != null) $key: $name,');
        } else if (field.required) {
          w.line('$key: ${encodeValue(field.type, name)},');
        } else if (isModel && defaultsToEmpty(field.type)) {
          w.line(
              'if ($name.isNotEmpty) $key: ${encodeValue(field.type, name)},');
        } else {
          w.line(
              'if ($name != null) $key: ${encodeValue(field.type, '$name!')},');
        }
      }
    }, close: '};');
  }

  void _emitMultipartEncoders(ClassIr c, DartWriter w) {
    w.doc(null,
        fallback:
            'The non-file parts of the `multipart/form-data` body; a `Map` or `List` value is sent JSON-encoded.');
    final fields = c.fields.where((f) => f.type is! IrFile).toList();
    if (fields.isEmpty) {
      w.line('Map<String, Object?> toFields() => const <String, Object?>{};');
    } else {
      w.block('Map<String, Object?> toFields() => {', () {
        for (final field in fields) {
          final key = dartStringLiteral(field.wireName);
          final name = field.dartName;
          if (field.type is IrJson) {
            w.line('if ($name != null) $key: $name,');
          } else if (field.required) {
            w.line('$key: ${encodeValue(field.type, name)},');
          } else {
            w.line(
                'if ($name != null) $key: ${encodeValue(field.type, '$name!')},');
          }
        }
      }, close: '};');
    }
    w.line();
    w.doc(null, fallback: 'The file parts of the `multipart/form-data` body.');
    final files = c.fields.where((f) => f.type is IrFile).toList();
    if (files.isEmpty) {
      w.line(
          'Map<String, BrevoFile> toFiles() => const <String, BrevoFile>{};');
    } else {
      w.block('Map<String, BrevoFile> toFiles() => {', () {
        for (final field in files) {
          final key = dartStringLiteral(field.wireName);
          if (field.required) {
            w.line('$key: ${field.dartName},');
          } else {
            w.line('if (${field.dartName} != null) $key: ${field.dartName}!,');
          }
        }
      }, close: '};');
    }
  }

  void _emitEnum(EnumIr e, DartWriter w) {
    w.doc(e.docs, fallback: 'The `${e.enumName}` values of the Brevo API.');
    w.block('final class ${e.enumName} extends BrevoOpenEnum {', () {
      w.line('const ${e.enumName}._(super.value);');
      w.line();
      w.doc(null, fallback: 'Wraps a value this package does not know.');
      w.line('const ${e.enumName}.unknown(super.value);');
      for (final value in e.values) {
        w.line();
        w.doc(null, fallback: 'The `${value.wire}` value.');
        w.line(
            'static const ${value.dartName} = ${e.enumName}._(${dartString(value.wire)});');
      }
      w.line();
      w.doc(null,
          fallback: 'The values known when this package was generated.');
      w.line(
          'static const values = [${e.values.map((v) => v.dartName).join(', ')}];');
      w.line();
      w.doc(null,
          fallback:
              'Decodes a wire value, preserving one this package does not know.');
      w.block(
          'factory ${e.enumName}.fromWire(String value) => values.firstWhere(',
          () {
        w.line('(known) => known.value == value,');
        w.line('orElse: () => ${e.enumName}.unknown(value),');
      }, close: ');');
      w.line();
      w.line('@override');
      w.line('bool get isKnown => values.contains(this);');
    });
  }

  String _emitNamespace(NamespaceIr namespace) {
    final path = _locations[namespace.className]!;
    final w = DartWriter();
    final referenced = <String>{};
    final core = <String>{'client.dart', 'request_options.dart'};
    final dart = <String>{};
    var usesJsonReading = false;
    for (final op in namespace.operations) {
      if (op.bodyClass != null) referenced.add(op.bodyClass!);
      if (op.pathParams.isNotEmpty) core.add('path_encoding.dart');
      for (final p in [...op.pathParams, ...op.queryParams]) {
        referenced.addAll(referencedTypeNames(p.type));
      }
      if (op.paged != null) core.add('offset_page.dart');
      switch (op.response) {
        case ObjectResponse(:final className):
          referenced.add(className);
          usesJsonReading = true;
        case ListResponse(:final element):
          referenced.addAll(referencedTypeNames(element));
          usesJsonReading = true;
        case BytesResponse():
          dart.add('typed_data');
        case VoidResponse():
          break;
      }
    }
    if (usesJsonReading) core.add('json_reading.dart');
    w.line(_header);
    _imports(path, referenced, core: core, dart: dart).forEach(w.line);
    w.line();
    w.doc(null,
        fallback:
            'The `${namespace.name}` resource of the Brevo API: `client.${namespace.name}`.');
    w.block('final class ${namespace.className} {', () {
      w.doc(null, fallback: 'Creates the resource backed by [_client].');
      w.line('const ${namespace.className}(this._client);');
      w.line();
      w.line('final BrevoClient _client;');
      final operations = namespace.operations.toList()
        ..sort((a, b) => a.methodName.compareTo(b.methodName));
      for (final op in operations) {
        w.line();
        _emitOperation(op, w);
        if (op.paged != null) {
          w.line();
          _emitPagedOperation(op, w);
        }
      }
    });
    return w.toString();
  }

  String _paramType(ParamIr param) =>
      param.type is IrJson ? 'Object' : dartType(param.type);

  List<String> _signatureParts(OperationIr op, {bool named = true}) {
    final positional = <String>[
      if (op.bodyClass != null) '${op.bodyClass} request',
    ];
    final namedParts = <String>[
      for (final p in op.pathParams) 'required ${_paramType(p)} ${p.dartName}',
      for (final q in op.queryParams)
        q.required
            ? 'required ${_paramType(q)} ${q.dartName}'
            : '${_paramType(q)}? ${q.dartName}',
      'BrevoRequestOptions? options',
    ];
    return [
      ...positional,
      if (named) '{${namedParts.join(', ')}}',
    ];
  }

  void _emitOperation(OperationIr op, DartWriter w) {
    final returnType = _returnType(op.response);
    final signature = _signatureParts(op).join(', ');
    final docLines = StringBuffer();
    docLines.writeln('`${op.httpMethod} ${op.pathTemplate}`');
    if (op.docs != null && op.docs!.isNotEmpty) {
      docLines.writeln();
      docLines.writeln(op.docs);
    }
    for (final p in [...op.pathParams, ...op.queryParams]) {
      if (p.docs != null && p.docs!.isNotEmpty) {
        docLines.writeln();
        docLines.writeln('[${p.dartName}]: ${p.docs}');
      }
    }
    w.doc(docLines.toString(),
        fallback: '`${op.httpMethod} ${op.pathTemplate}`');
    if (op.deprecated) w.line("@Deprecated('Deprecated by Brevo.')");

    final args = <String>[
      'method: ${dartStringLiteral(op.httpMethod)}',
      'path: ${_pathExpression(op)}',
      if (op.queryParams.isNotEmpty) 'query: ${_queryLiteral(op)}',
    ];
    final bodyClass = op.bodyClass;
    final multipart = bodyClass != null && ir.classes[bodyClass]!.multipart;
    if (bodyClass != null && !multipart) args.add('body: request.toJson()');
    if (multipart) {
      args
        ..add('fields: request.toFields()')
        ..add('files: request.toFiles()');
    }
    args.add('options: options');
    String invoke(String method) => multipart
        ? '_client.requestMultipart(${args.join(', ')})'
        : '_client.$method(${args.join(', ')})';

    switch (op.response) {
      case VoidResponse():
        w.block('$returnType ${op.methodName}($signature) async {', () {
          w.line('await ${invoke('requestVoid')};');
        });
      case BytesResponse():
        w.line(
            '$returnType ${op.methodName}($signature) => ${invoke('requestBytes')};');
      case ObjectResponse(:final className):
        w.block('$returnType ${op.methodName}($signature) async {', () {
          w.line('final json = await ${invoke('requestJson')};');
          w.line(
              'return $className.fromJson(brevoRequireJsonObject(json ?? const <String, Object?>{}, objectName: ${dartStringLiteral(className)}));');
        });
      case ListResponse(:final element):
        w.block('$returnType ${op.methodName}($signature) async {', () {
          w.line('final json = await ${invoke('requestJson')};');
          w.line(
              'final items = brevoRequireJsonList(json ?? const <Object?>[], objectName: ${dartStringLiteral(op.methodName)});');
          w.line('return ${_decodeListItems(element, op.methodName)};');
        });
    }
  }

  void _emitPagedOperation(OperationIr op, DartWriter w) {
    final paged = op.paged!;
    final limit = op.queryParams.firstWhere((q) => q.wireName == 'limit');
    final defaultLimit =
        limit.defaultValue is int ? limit.defaultValue as int : 50;
    final others = op.queryParams
        .where((q) => q.wireName != 'limit' && q.wireName != 'offset')
        .toList();
    final namedParts = <String>[
      for (final p in op.pathParams) 'required ${_paramType(p)} ${p.dartName}',
      'int limit = $defaultLimit',
      'int offset = 0',
      for (final q in others)
        q.required
            ? 'required ${_paramType(q)} ${q.dartName}'
            : '${_paramType(q)}? ${q.dartName}',
      'BrevoRequestOptions? options',
    ];
    final positional = op.bodyClass == null ? '' : '${op.bodyClass} request, ';
    final forward = <String>[
      if (op.bodyClass != null) 'request',
      for (final p in op.pathParams) '${p.dartName}: ${p.dartName}',
      'limit: limit',
      for (final q in others) '${q.dartName}: ${q.dartName}',
      'options: options',
    ];
    final itemClass = paged.itemClass;
    final listField = ir
        .classes[(op.response as ObjectResponse).className]!.fields
        .firstWhere((f) => f.wireName == paged.listWireName)
        .dartName;
    w.doc(
        'Calls [${op.methodName}] and wraps the result in a [BrevoOffsetPage], so the following pages can be fetched with `nextPage()` or every item walked with `autoPaging()`.',
        fallback: '');
    if (op.deprecated) w.line("@Deprecated('Deprecated by Brevo.')");
    w.block(
        'Future<BrevoOffsetPage<$itemClass>> ${op.methodName}Paged($positional{${namedParts.join(', ')}}) async {',
        () {
      w.line('final page = await ${op.methodName}(${[
        ...forward,
        'offset: offset'
      ].join(', ')});');
      w.block('return BrevoOffsetPage<$itemClass>(', () {
        w.line('items: page.$listField,');
        w.line('limit: limit,');
        w.line('offset: offset,');
        w.line('count: page.count,');
        w.line('(next) => ${op.methodName}Paged(${[
          ...forward,
          'offset: next'
        ].join(', ')}),'
            .replaceFirst('(next)', 'fetchPage: (next)'));
      }, close: ');');
    });
  }

  String _decodeListItems(IrType element, String owner) => switch (element) {
        IrRef(:final className) =>
          '[for (final item in items) $className.fromJson(brevoRequireJsonObject(item, objectName: ${dartStringLiteral(className)}))]',
        IrString() => 'items.whereType<String>().toList(growable: false)',
        IrInt() => 'items.whereType<int>().toList(growable: false)',
        IrJson() => 'items',
        IrJsonMap() =>
          'items.whereType<Map<String, Object?>>().toList(growable: false)',
        _ => throw StateError(
            '$owner: unsupported list response element ${dartType(element)}'),
      };

  String _queryLiteral(OperationIr op) {
    final entries = op.queryParams.map((q) {
      final key = dartStringLiteral(q.wireName);
      final value = switch (q.type) {
        IrEnumRef() =>
          q.required ? '${q.dartName}.value' : '${q.dartName}?.value',
        IrList(element: IrEnumRef()) => q.required
            ? '[for (final item in ${q.dartName}) item.value]'
            : '${q.dartName} == null ? null : [for (final item in ${q.dartName}!) item.value]',
        _ => q.dartName,
      };
      return '$key: $value';
    });
    return '<String, Object?>{${entries.join(', ')}}';
  }

  String _pathExpression(OperationIr op) {
    var template = op.pathTemplate.replaceAll(r'$', r'\$');
    for (final p in op.pathParams) {
      final value = p.type is IrEnumRef ? '${p.dartName}.value' : p.dartName;
      template = template.replaceAll(
          '{${p.wireName}}', '\${brevoPathSegment($value)}');
    }
    return "'$template'";
  }

  String _returnType(ResponseIr response) => switch (response) {
        VoidResponse() => 'Future<void>',
        BytesResponse() => 'Future<Uint8List>',
        ObjectResponse(:final className) => 'Future<$className>',
        ListResponse(:final element) => 'Future<List<${dartType(element)}>>',
      };

  String _emitClientResources() {
    final w = DartWriter();
    w.line(_header);
    final imports = <String>{
      "import '../core/client.dart';",
      for (final namespace in ir.namespaces.values)
        "import '${namespace.name}/resource.dart';",
    }.toList()
      ..sort();
    imports.forEach(w.line);
    w.line();
    w.doc(null,
        fallback:
            'The typed resources of the Brevo API, reachable as `client.<resource>`.');
    w.block('extension BrevoClientResources on BrevoClient {', () {
      final namespaces = ir.namespaces.values.toList()
        ..sort((a, b) => a.name.compareTo(b.name));
      var first = true;
      for (final namespace in namespaces) {
        if (!first) {
          w.line();
        }
        first = false;
        w.doc(null,
            fallback:
                '`client.${namespace.name}` operations (${namespace.operations.length}).');
        w.line(
            '${namespace.className} get ${namespace.name} => ${namespace.className}(this);');
      }
    });
    return w.toString();
  }

  String _emitBarrel() {
    final w = DartWriter();
    w.line(_header);
    final files = <String>{
      ..._locations.values,
      'client_resources.dart',
    }.toList()
      ..sort();
    for (final file in files) {
      w.line("export '$file';");
    }
    return w.toString();
  }

  String _emitDecodeTest() {
    final w = DartWriter();
    w.line(_header);
    w.line("import 'dart:convert';");
    w.line("import 'dart:io';");
    w.line();
    w.line("import 'package:brevo_api/brevo_api.dart';");
    w.line("import 'package:test/test.dart';");
    w.line();
    w.block(
        'final Map<String, Object Function(Map<String, Object?>)> _decoders = {',
        () {
      for (final c in ir.classes.values) {
        if (c.multipart) continue;
        w.line('${dartStringLiteral(c.className)}: ${c.className}.fromJson,');
      }
    }, close: '};');
    w.line();
    w.block('const Map<String, Map<String, Object?>> _minimal = {', () {
      for (final c in ir.classes.values) {
        if (c.multipart) continue;
        w.line('${dartStringLiteral(c.className)}: ${_minimalLiteral(c, {
              c.className
            })},');
      }
    }, close: '};');
    w.line();
    w.block('void main() {', () {
      w.line(
          "final examples = (jsonDecode(File('test/generated/response_examples.json').readAsStringSync()) as List<Object?>).cast<Map<String, Object?>>();");
      w.block('for (final entry in _decoders.entries) {', () {
        w.block("test('\${entry.key} decodes a minimal payload', () {", () {
          w.line('final decoded = entry.value(_minimal[entry.key]!);');
          w.line(
              'expect((decoded as dynamic).toJson(), isA<Map<String, Object?>>());');
        }, close: '});');
      });
      w.block('for (final example in examples) {', () {
        w.line("final className = example['className']! as String;");
        w.block(
            "test('\${example['operation']} example decodes as \$className', () {",
            () {
          w.line('final decoder = _decoders[className]!;');
          w.line(
              "final decoded = decoder(example['body']! as Map<String, Object?>);");
          w.line(
              'expect((decoded as dynamic).toJson(), isA<Map<String, Object?>>());');
        }, close: '});');
      });
    });
    return w.toString();
  }

  String _minimalLiteral(ClassIr c, Set<String> visiting) {
    final entries = [
      for (final field in c.fields)
        if (field.required)
          '${dartStringLiteral(field.wireName)}: ${_stubJson(field.type, visiting)}',
    ];
    return entries.isEmpty
        ? '<String, Object?>{}'
        : '<String, Object?>{${entries.join(', ')}}';
  }

  String _stubJson(IrType type, Set<String> visiting) => switch (type) {
        IrString() => "'x'",
        IrInt() => '1',
        IrDouble() => '1.0',
        IrBool() => 'true',
        IrJson() => "'x'",
        IrJsonMap() => '<String, Object?>{}',
        IrFile() => "'x'",
        IrList(:final element) => '<Object?>[${_stubJson(element, visiting)}]',
        IrEnumRef(:final enumName) =>
          dartStringLiteral(ir.enums[enumName]!.values.first.wire),
        IrRef(:final className) => visiting.contains(className)
            ? '<String, Object?>{}'
            : _minimalLiteral(ir.classes[className]!, {...visiting, className}),
      };

  String _stubDart(IrType type, Set<String> visiting) => switch (type) {
        IrString() => "'x'",
        IrInt() => '1',
        IrDouble() => '1.0',
        IrBool() => 'true',
        IrJson() => "'x'",
        IrJsonMap() => 'const <String, Object?>{}',
        IrFile() => "BrevoFile(bytes: Uint8List(0), filename: 'x')",
        IrList(:final element) => '[${_stubDart(element, visiting)}]',
        IrEnumRef(:final enumName) =>
          '${ir.enums[enumName]!.enumName}.${ir.enums[enumName]!.values.first.dartName}',
        IrRef(:final className) => _constructorStub(className, visiting),
      };

  String _constructorStub(String className, Set<String> visiting) {
    final c = ir.classes[className]!;
    final next = {...visiting, className};
    final args = <String>[];
    for (final field in c.fields) {
      if (!field.required) continue;
      final refs = referencedTypeNames(field.type);
      if (refs.any(next.contains)) {
        throw StateError(
            '$className.${field.dartName} is a required field of a recursive type');
      }
      args.add('${field.dartName}: ${_stubDart(field.type, next)}');
    }
    return '$className(${args.join(', ')})';
  }

  String _emitMockTest() {
    final w = DartWriter();
    w.line(_header);
    w.line("@Tags(['mock'])");
    w.line('library;');
    w.line();
    w.line("import 'dart:io';");
    w.line("import 'dart:typed_data';");
    w.line();
    w.line("import 'package:brevo_api/brevo_api.dart';");
    w.line("import 'package:test/test.dart';");
    w.line();
    w.block('void main() {', () {
      w.line("final host = Platform.environment['BREVO_MOCK_HOST'] ?? '';");
      w.block('final client = BrevoClient(', () {
        w.line("apiKey: 'mock',");
        w.line("baseUrl: Uri.parse('http://\$host'),");
        w.line('maxRetries: 0,');
      }, close: ');');
      w.block('setUpAll(() {', () {
        w.block('if (host.isEmpty) {', () {
          w.line(
              "fail('BREVO_MOCK_HOST is empty; start tool/mock/run_wiremock.sh and set BREVO_MOCK_HOST=127.0.0.1:8089.');");
        });
      }, close: '});');
      w.line('tearDownAll(client.close);');
      final byNamespace = <String, List<MockCaseIr>>{};
      for (final mockCase in ir.mockCases) {
        final op = _operationsByKey[mockCase.operationKey]!;
        byNamespace.putIfAbsent(op.namespace, () => []).add(mockCase);
      }
      for (final entry in byNamespace.entries.toList()
        ..sort((a, b) => a.key.compareTo(b.key))) {
        w.line();
        w.block("group(${dartStringLiteral(entry.key)}, () {", () {
          final cases = entry.value.toList()
            ..sort((a, b) => _operationsByKey[a.operationKey]!
                .methodName
                .compareTo(_operationsByKey[b.operationKey]!.methodName));
          for (final mockCase in cases) {
            final op = _operationsByKey[mockCase.operationKey]!;
            w.block(
                "test(${dartStringLiteral('${op.methodName} (${op.key})')}, () async {",
                () {
              w.line(
                  'await client.${op.namespace}.${op.methodName}(${_mockArgs(op, mockCase).join(', ')});');
            }, close: '});');
          }
        }, close: '});');
      }
    });
    return w.toString();
  }

  List<String> _mockArgs(OperationIr op, MockCaseIr mockCase) {
    final args = <String>[];
    final bodyClass = op.bodyClass;
    if (bodyClass != null) {
      args.add(_constructorStub(bodyClass, const {}));
    }
    for (final p in op.pathParams) {
      final value = mockCase.pathParams[p.wireName]!;
      args.add('${p.dartName}: ${_mockValue(p, value)}');
    }
    for (final q in op.queryParams) {
      final value = mockCase.queryParams[q.wireName];
      if (value == null) {
        if (q.required) {
          args.add('${q.dartName}: ${_stubDart(q.type, const {})}');
        }
        continue;
      }
      args.add('${q.dartName}: ${_mockValue(q, value)}');
    }
    return args;
  }

  String _mockValue(ParamIr param, String value) {
    String scalar(IrType type) => switch (type) {
          IrInt() => int.tryParse(value)?.toString() ??
              (throw StateError(
                  '${param.wireName}: mapping value "$value" is not an int')),
          IrDouble() => double.tryParse(value)?.toString() ??
              (throw StateError(
                  '${param.wireName}: mapping value "$value" is not a number')),
          IrBool() => value == 'true' ? 'true' : 'false',
          IrEnumRef(:final enumName) =>
            '$enumName.fromWire(${dartStringLiteral(value)})',
          _ => dartStringLiteral(value),
        };
    return switch (param.type) {
      IrList(:final element) => '[${scalar(element)}]',
      final type => scalar(type),
    };
  }

  String _emitResponseExamples() {
    final examples = <Map<String, Object?>>[];
    for (final mockCase in ir.mockCases) {
      final op = _operationsByKey[mockCase.operationKey]!;
      final response = op.response;
      if (response is! ObjectResponse) continue;
      final body = mockCase.responseBody;
      if (body is! String) continue;
      final decoded = jsonDecode(body);
      if (decoded is! Map<String, Object?>) continue;
      examples.add({
        'operation': op.key,
        'className': response.className,
        'body': decoded,
      });
    }
    examples.sort((a, b) =>
        (a['operation']! as String).compareTo(b['operation']! as String));
    return '${const JsonEncoder.withIndent('  ').convert(examples)}\n';
  }
}
