import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;

import '../operation_key.dart';

/// Extracts the public API surface of a `getbrevo/brevo-node` release —
/// namespaces, method names, request and response type names and query
/// parameter order — and writes it to `tool/spec/resources.yaml`, keyed by
/// HTTP method and path so it lines up with the vendored specification,
/// which lacks `operationId` on a third of its operations.
///
/// Usage: `dart run tool/upstream/extract_resources.dart --tag v6.0.3`
///
/// Every method found upstream must map to exactly one operation of the
/// vendored specification and vice versa; a mismatch is a failure, so a
/// spec bump and an SDK bump are always reconciled explicitly.
Future<void> main(List<String> arguments) async {
  final tag = _parseTag(arguments);
  final spec =
      json.decode(File('tool/spec/brevo-openapi.json').readAsStringSync())
          as Map<String, Object?>;
  final specOperations = _specOperations(spec);

  final staging = Directory.systemTemp.createTempSync('brevo_node_');
  try {
    final archive = File('${staging.path}/brevo-node.tar.gz');
    final url = Uri.parse(
        'https://codeload.github.com/getbrevo/brevo-node/tar.gz/refs/tags/$tag');
    final response = await http.get(url);
    if (response.statusCode != 200) {
      throw StateError(
        'Failed to download brevo-node at tag "$tag" from $url: '
        'HTTP ${response.statusCode}. Confirm the tag exists in '
        'https://github.com/getbrevo/brevo-node/tags.',
      );
    }
    archive.writeAsBytesSync(response.bodyBytes);
    final untar =
        await Process.run('tar', ['-xzf', archive.path, '-C', staging.path]);
    if (untar.exitCode != 0) {
      throw StateError('tar failed: ${untar.stderr}');
    }
    final root = staging
        .listSync()
        .whereType<Directory>()
        .singleWhere((dir) => dir.path.contains('brevo-node'));
    final resources = Directory('${root.path}/src/api/resources');
    if (!resources.existsSync()) {
      throw StateError('No src/api/resources in the brevo-node tarball.');
    }

    final extracted = <String, _UpstreamOperation>{};
    final namespaces = resources.listSync().whereType<Directory>().toList()
      ..sort((a, b) => a.path.compareTo(b.path));
    for (final namespace in namespaces) {
      final client = File('${namespace.path}/client/Client.ts');
      if (!client.existsSync()) continue;
      final name = namespace.path.split('/').last;
      for (final operation in _parseClient(name, client.readAsStringSync())) {
        final key = operation.key;
        if (extracted.containsKey(key)) {
          throw StateError(
              'Both ${extracted[key]!.qualified} and ${operation.qualified} map to $key');
        }
        extracted[key] = operation;
      }
    }

    final unmatchedUpstream =
        extracted.keys.toSet().difference(specOperations.keys.toSet());
    final unmatchedSpec =
        specOperations.keys.toSet().difference(extracted.keys.toSet());
    if (unmatchedUpstream.isNotEmpty || unmatchedSpec.isNotEmpty) {
      final buffer = StringBuffer('Upstream and specification disagree:\n');
      for (final key in unmatchedUpstream.toList()..sort()) {
        buffer.writeln(
            '  only in brevo-node: $key (${extracted[key]!.qualified})');
      }
      for (final key in unmatchedSpec.toList()..sort()) {
        buffer.writeln('  only in the spec:   $key (${specOperations[key]})');
      }
      throw StateError(buffer.toString());
    }

    final yaml = StringBuffer()
      ..writeln(
          '# GENERATED by tool/upstream/extract_resources.dart — do not edit by hand.')
      ..writeln(
          '# Namespaces, method names, type names and query order of @getbrevo/brevo,')
      ..writeln('# keyed by HTTP method and the specification path.')
      ..writeln('upstream:')
      ..writeln('  package: "@getbrevo/brevo"')
      ..writeln('  tag: $tag')
      ..writeln('operations:');
    final keys = extracted.keys.toList()..sort();
    for (final key in keys) {
      final op = extracted[key]!;
      yaml
        ..writeln('  "${specOperations[key]}":')
        ..writeln('    namespace: ${op.namespace}')
        ..writeln('    method: ${op.method}');
      if (op.requestType != null) {
        yaml.writeln('    request: ${op.requestType}');
      }
      yaml.writeln('    response: ${op.responseType ?? 'void'}');
      if (op.queryParams.isNotEmpty) {
        yaml.writeln(
            '    query: [${op.queryParams.map((q) => '"$q"').join(', ')}]');
      }
    }
    File('tool/spec/resources.yaml').writeAsStringSync(yaml.toString());
    File('tool/spec/UPSTREAM_VERSION').writeAsStringSync('$tag\n');
    stdout.writeln(
        'Wrote tool/spec/resources.yaml: ${extracted.length} operations across ${namespaces.length} namespaces from brevo-node $tag.');
  } finally {
    staging.deleteSync(recursive: true);
  }
}

String _parseTag(List<String> arguments) {
  final index = arguments.indexOf('--tag');
  if (index == -1 || index + 1 >= arguments.length) {
    throw ArgumentError('Usage: extract_resources.dart --tag vX.Y.Z');
  }
  final tag = arguments[index + 1];
  if (!RegExp(r'^v\d+\.\d+\.\d+').hasMatch(tag)) {
    throw ArgumentError('"$tag" is not a release tag like v6.0.3');
  }
  return tag;
}

/// Normalised key (`GET /contacts/{}`) → specification key
/// (`GET /contacts/{identifier}`).
Map<String, String> _specOperations(Map<String, Object?> spec) {
  final result = <String, String>{};
  for (final entry in (spec['paths']! as Map<String, Object?>).entries) {
    for (final method in (entry.value as Map<String, Object?>).keys) {
      if (!httpMethods.contains(method)) continue;
      final key = '${method.toUpperCase()} ${normalisePathTemplate(entry.key)}';
      if (result.containsKey(key)) {
        throw StateError('Two specification paths normalise to $key');
      }
      result[key] = '${method.toUpperCase()} ${entry.key}';
    }
  }
  return result;
}

final class _UpstreamOperation {
  const _UpstreamOperation({
    required this.namespace,
    required this.method,
    required this.httpMethod,
    required this.path,
    required this.requestType,
    required this.responseType,
    required this.queryParams,
  });

  final String namespace;
  final String method;
  final String httpMethod;
  final String path;
  final String? requestType;
  final String? responseType;
  final List<String> queryParams;

  String get key => '$httpMethod ${normalisePathTemplate(path)}';
  String get qualified => '$namespace.$method';
}

final RegExp _publicMethod = RegExp(r'^\s{4}public (\w+)\(', multiLine: true);
final RegExp _privateMethod =
    RegExp(r'^\s{4}private async __(\w+)\(', multiLine: true);
final RegExp _returnType =
    RegExp(r'\):\s*core\.HttpResponsePromise<([^>]+(?:<[^>]*>)?)>\s*\{');
final RegExp _requestType = RegExp(r'request:\s*Brevo\.(\w+)');
final RegExp _httpMethod = RegExp(r'\bmethod:\s*"([A-Z]+)"');
final RegExp _joinPath = RegExp(
    r'environments\.BrevoEnvironment\.Default,\s*(`(?:[^`\\]|\\.)*`|"(?:[^"\\]|\\.)*")\s*,?\s*\)');
final RegExp _pathParam = RegExp(r'\$\{core\.url\.encodePathParam\((\w+)\)\}');
final RegExp _queryBlock = RegExp(
    r'const _queryParams(?::\s*Record<string, unknown>)?\s*=\s*\{([\s\S]*?)\n\s*\};');
final RegExp _queryKey =
    RegExp(r'^\s*("?[\w\[\]\-.]+"?)\s*[:,]', multiLine: true);

List<_UpstreamOperation> _parseClient(String namespace, String source) {
  final publicMatches = _publicMethod.allMatches(source).toList();
  final privateMatches = {
    for (final match in _privateMethod.allMatches(source))
      match.group(1)!: match.start
  };
  final operations = <_UpstreamOperation>[];
  for (var i = 0; i < publicMatches.length; i++) {
    final match = publicMatches[i];
    final name = match.group(1)!;
    final end = i + 1 < publicMatches.length
        ? publicMatches[i + 1].start
        : source.length;
    final declaration = source.substring(match.start, end);
    final returnMatch = _returnType.firstMatch(declaration);
    if (returnMatch == null) {
      throw StateError('$namespace.$name: no HttpResponsePromise return type');
    }
    final privateStart = privateMatches[name];
    if (privateStart == null) {
      throw StateError('$namespace.$name: no private __$name implementation');
    }
    final nextPrivate = privateMatches.values
        .where((start) => start > privateStart)
        .fold<int>(source.length, (a, b) => a < b ? a : b);
    final body = source.substring(privateStart, nextPrivate);
    final httpMethod = _httpMethod.firstMatch(body)?.group(1);
    if (httpMethod == null) {
      throw StateError('$namespace.$name: no HTTP method');
    }
    final joined = _joinPath.firstMatch(body)?.group(1);
    if (joined == null) {
      throw StateError('$namespace.$name: no core.url.join path');
    }
    final path = joined
        .substring(1, joined.length - 1)
        .replaceAllMapped(_pathParam, (m) => '{${m.group(1)}}');
    final queryBlock = _queryBlock.firstMatch(body)?.group(1);
    final queryParams = <String>[];
    if (queryBlock != null) {
      for (final key in _queryKey.allMatches(queryBlock)) {
        queryParams.add(key.group(1)!.replaceAll('"', ''));
      }
    }
    final responseType = returnMatch.group(1)!.trim();
    operations.add(_UpstreamOperation(
      namespace: namespace,
      method: name,
      httpMethod: httpMethod,
      path: path,
      requestType: _requestType.firstMatch(declaration)?.group(1),
      responseType: responseType == 'void'
          ? null
          : responseType.replaceFirst('Brevo.', ''),
      queryParams: queryParams,
    ));
  }
  return operations;
}
